"""nomes de infraestrutura em ingles

Renomeia tabelas, colunas e enums que descrevem a maquinaria da aplicacao (provider,
capability, execucao, log, custo), mais as colunas genericas de metadado (criado_em,
ativo, descricao...) em todas as tabelas. O vocabulario do PNCP e da licitacao — item,
termo, documento, catalogo, par, grupo, faixa_preco — continua em portugues.

RENAME nao reescreve linha nenhuma, e o downgrade desfaz tudo na ordem inversa.

Revision ID: 0011
Revises: 0010
"""
from alembic import op

revision = "0011"
down_revision = "0010"
branch_labels = None
depends_on = None

UP = """
ALTER TYPE capacidade RENAME TO capability;
ALTER TYPE status_etapa RENAME TO step_status;
ALTER TYPE acao_execucao RENAME TO run_action;
ALTER TYPE estrategia_extracao RENAME TO extraction_strategy;
ALTER TYPE modo_run RENAME TO run_mode;
ALTER TYPE status_run RENAME TO run_status;
ALTER TYPE capability RENAME VALUE 'pareamento' TO 'matching';
ALTER TYPE extraction_strategy RENAME VALUE 'janela' TO 'window';
ALTER TYPE extraction_strategy RENAME VALUE 'completa' TO 'full';
ALTER TYPE extraction_strategy RENAME VALUE 'visao' TO 'vision';
ALTER TYPE step_status RENAME VALUE 'nao_iniciada' TO 'not_started';
ALTER TYPE step_status RENAME VALUE 'aguardando_aprovacao' TO 'awaiting_approval';
ALTER TYPE step_status RENAME VALUE 'executando' TO 'running';
ALTER TYPE step_status RENAME VALUE 'concluida' TO 'finished';
ALTER TYPE step_status RENAME VALUE 'desatualizada' TO 'outdated';
ALTER TYPE step_status RENAME VALUE 'falhou' TO 'failed';
ALTER TYPE step_status RENAME VALUE 'cancelada' TO 'cancelled';
ALTER TYPE step_status RENAME VALUE 'pulada' TO 'skipped';
ALTER TYPE run_action RENAME VALUE 'atualizar' TO 'update';
ALTER TYPE run_action RENAME VALUE 'retomar' TO 'resume';
ALTER TYPE run_action RENAME VALUE 'refazer' TO 'redo';
ALTER TYPE run_mode RENAME VALUE 'assistido' TO 'assisted';
ALTER TYPE run_mode RENAME VALUE 'sequencial' TO 'sequential';
ALTER TYPE run_mode RENAME VALUE 'amostra' TO 'sample';
ALTER TYPE run_mode RENAME VALUE 'simulacao' TO 'simulation';
ALTER TYPE run_status RENAME VALUE 'aberto' TO 'open';
ALTER TYPE run_status RENAME VALUE 'concluido' TO 'finished';
ALTER TYPE run_status RENAME VALUE 'abortado' TO 'aborted';
ALTER TABLE capacidade_provedor RENAME COLUMN capacidade TO capability;
ALTER TABLE capacidade_provedor RENAME COLUMN modelo TO model;
ALTER TABLE capacidade_provedor RENAME COLUMN provedor TO provider;
ALTER TABLE catalogo_item RENAME COLUMN ativo TO active;
ALTER TABLE catalogo_item RENAME COLUMN atualizado_em TO updated_at;
ALTER TABLE catalogo_item RENAME COLUMN criado_em TO created_at;
ALTER TABLE catalogo_item RENAME COLUMN descricao TO description;
ALTER TABLE catalogo_raw RENAME COLUMN descricao TO description;
ALTER TABLE coleta_progresso RENAME COLUMN concluido_em TO finished_at;
ALTER TABLE coleta_watermark RENAME COLUMN atualizado_em TO updated_at;
ALTER TABLE config_valor RENAME COLUMN chave TO key;
ALTER TABLE config_valor RENAME COLUMN config_versao_id TO config_version_id;
ALTER TABLE config_valor RENAME COLUMN valor TO value;
ALTER TABLE config_versao RENAME COLUMN criado_em TO created_at;
ALTER TABLE config_versao RENAME COLUMN criado_por TO created_by;
ALTER TABLE config_versao RENAME COLUMN notas TO notes;
ALTER TABLE config_versao RENAME COLUMN rotulo TO label;
ALTER TABLE documento RENAME COLUMN atualizado_em TO updated_at;
ALTER TABLE documento RENAME COLUMN criado_em TO created_at;
ALTER TABLE documento_extracao RENAME COLUMN criado_em TO created_at;
ALTER TABLE documento_extracao RENAME COLUMN custo_usd TO cost_usd;
ALTER TABLE documento_extracao RENAME COLUMN duracao_ms TO duration_ms;
ALTER TABLE documento_extracao RENAME COLUMN modelo TO model;
ALTER TABLE documento_extracao RENAME COLUMN provedor TO provider;
ALTER TABLE embedding_cache RENAME COLUMN criado_em TO created_at;
ALTER TABLE embedding_cache RENAME COLUMN dimensao TO dimension;
ALTER TABLE embedding_cache RENAME COLUMN modelo TO model;
ALTER TABLE embedding_cache RENAME COLUMN provedor TO provider;
ALTER TABLE embedding_cache RENAME COLUMN vetor TO vector;
ALTER TABLE erro_item RENAME COLUMN chave TO key;
ALTER TABLE erro_item RENAME COLUMN criado_em TO created_at;
ALTER TABLE erro_item RENAME COLUMN etapa TO step;
ALTER TABLE erro_item RENAME COLUMN mensagem TO message;
ALTER TABLE erro_item RENAME COLUMN resolvido TO resolved;
ALTER TABLE erro_item RENAME COLUMN tentativas TO attempts;
ALTER TABLE erro_item RENAME COLUMN tipo_erro TO error_type;
ALTER TABLE execucao_lock RENAME COLUMN adquirido_em TO acquired_at;
ALTER TABLE execucao_lock RENAME COLUMN expira_em TO expires_at;
ALTER TABLE export RENAME COLUMN criado_em TO created_at;
ALTER TABLE faixa_preco RENAME COLUMN config_versao_id TO config_version_id;
ALTER TABLE grupo_item RENAME COLUMN criado_em TO created_at;
ALTER TABLE grupo_permitido RENAME COLUMN ativo TO active;
ALTER TABLE grupo_permitido RENAME COLUMN atualizado_em TO updated_at;
ALTER TABLE grupo_permitido RENAME COLUMN criado_em TO created_at;
ALTER TABLE grupo_permitido RENAME COLUMN criado_por TO created_by;
ALTER TABLE grupo_permitido RENAME COLUMN nome TO name;
ALTER TABLE item RENAME COLUMN criado_em TO created_at;
ALTER TABLE item_enriquecido RENAME COLUMN criado_em TO created_at;
ALTER TABLE llm_chamada RENAME COLUMN capacidade TO capability;
ALTER TABLE llm_chamada RENAME COLUMN chave TO key;
ALTER TABLE llm_chamada RENAME COLUMN criado_em TO created_at;
ALTER TABLE llm_chamada RENAME COLUMN custo_usd TO cost_usd;
ALTER TABLE llm_chamada RENAME COLUMN duracao_ms TO duration_ms;
ALTER TABLE llm_chamada RENAME COLUMN etapa TO step;
ALTER TABLE llm_chamada RENAME COLUMN modelo TO model;
ALTER TABLE llm_chamada RENAME COLUMN prompt_versao_id TO prompt_version_id;
ALTER TABLE llm_chamada RENAME COLUMN provedor TO provider;
ALTER TABLE llm_chamada RENAME COLUMN sucesso TO success;
ALTER TABLE notificacao_destinatario RENAME COLUMN ativo TO active;
ALTER TABLE notificacao_destinatario RENAME COLUMN criado_em TO created_at;
ALTER TABLE notificacao_destinatario RENAME COLUMN nome TO name;
ALTER TABLE par RENAME COLUMN atualizado_em TO updated_at;
ALTER TABLE par RENAME COLUMN decisao_final TO final_decision;
ALTER TABLE pdm_permitido RENAME COLUMN ativo TO active;
ALTER TABLE pdm_permitido RENAME COLUMN atualizado_em TO updated_at;
ALTER TABLE pdm_permitido RENAME COLUMN criado_em TO created_at;
ALTER TABLE pdm_permitido RENAME COLUMN criado_por TO created_by;
ALTER TABLE pdm_permitido RENAME COLUMN nome TO name;
ALTER TABLE prompt RENAME COLUMN capacidade TO capability;
ALTER TABLE prompt RENAME COLUMN descricao TO description;
ALTER TABLE prompt RENAME COLUMN nome TO name;
ALTER TABLE prompt_versao RENAME COLUMN ativa TO active;
ALTER TABLE prompt_versao RENAME COLUMN criado_em TO created_at;
ALTER TABLE prompt_versao RENAME COLUMN criado_por TO created_by;
ALTER TABLE prompt_versao RENAME COLUMN notas TO notes;
ALTER TABLE prompt_versao RENAME COLUMN prompt_nome TO prompt_name;
ALTER TABLE prompt_versao RENAME COLUMN versao TO version;
ALTER TABLE provedor RENAME COLUMN api_key_atualizada_em TO api_key_updated_at;
ALTER TABLE provedor RENAME COLUMN api_key_cifrada TO api_key_encrypted;
ALTER TABLE provedor RENAME COLUMN ativo TO active;
ALTER TABLE provedor RENAME COLUMN atualizado_em TO updated_at;
ALTER TABLE provedor RENAME COLUMN capacidades TO capabilities;
ALTER TABLE provedor RENAME COLUMN custo_in_por_mtok TO cost_in_per_mtok;
ALTER TABLE provedor RENAME COLUMN custo_out_por_mtok TO cost_out_per_mtok;
ALTER TABLE provedor RENAME COLUMN custo_usd_chamada TO cost_usd_per_call;
ALTER TABLE provedor RENAME COLUMN modelo_padrao TO default_model;
ALTER TABLE provedor RENAME COLUMN nome TO name;
ALTER TABLE provedor RENAME COLUMN permite_fallback TO allows_fallback;
ALTER TABLE provedor RENAME COLUMN prioridade TO priority;
ALTER TABLE provedor RENAME COLUMN rpm_limite TO rpm_limit;
ALTER TABLE provedor_status RENAME COLUMN latencia_ms TO latency_ms;
ALTER TABLE provedor_status RENAME COLUMN mensagem TO message;
ALTER TABLE provedor_status RENAME COLUMN provedor TO provider;
ALTER TABLE provedor_status RENAME COLUMN saudavel TO healthy;
ALTER TABLE provedor_status RENAME COLUMN verificado_em TO checked_at;
ALTER TABLE rotulo RENAME COLUMN criado_em TO created_at;
ALTER TABLE rotulo RENAME COLUMN decisao_final TO final_decision;
ALTER TABLE rotulo RENAME COLUMN modelo TO model;
ALTER TABLE rotulo RENAME COLUMN origem TO source;
ALTER TABLE run RENAME COLUMN concluido_em TO finished_at;
ALTER TABLE run RENAME COLUMN config_versao_id TO config_version_id;
ALTER TABLE run RENAME COLUMN criado_em TO created_at;
ALTER TABLE run RENAME COLUMN criado_por TO created_by;
ALTER TABLE run RENAME COLUMN custo_usd TO cost_usd;
ALTER TABLE run RENAME COLUMN limite_documentos TO document_limit;
ALTER TABLE run RENAME COLUMN modo TO mode;
ALTER TABLE run RENAME COLUMN rotulo TO label;
ALTER TABLE run RENAME COLUMN teto_custo_usd TO cost_cap_usd;
ALTER TABLE run_etapa RENAME COLUMN acao TO action;
ALTER TABLE run_etapa RENAME COLUMN aprovado_em TO approved_at;
ALTER TABLE run_etapa RENAME COLUMN aprovado_por TO approved_by;
ALTER TABLE run_etapa RENAME COLUMN concluida_em TO finished_at;
ALTER TABLE run_etapa RENAME COLUMN custo_usd TO cost_usd;
ALTER TABLE run_etapa RENAME COLUMN erros TO errors;
ALTER TABLE run_etapa RENAME COLUMN etapa TO step;
ALTER TABLE run_etapa RENAME COLUMN heartbeat_em TO heartbeat_at;
ALTER TABLE run_etapa RENAME COLUMN iniciada_em TO started_at;
ALTER TABLE run_etapa RENAME COLUMN mensagem_erro TO error_message;
ALTER TABLE run_etapa RENAME COLUMN metricas TO metrics;
ALTER TABLE run_etapa RENAME COLUMN params_efetivos TO effective_params;
ALTER TABLE run_etapa RENAME COLUMN processados TO processed;
ALTER TABLE run_log RENAME COLUMN contexto TO context;
ALTER TABLE run_log RENAME COLUMN criado_em TO created_at;
ALTER TABLE run_log RENAME COLUMN etapa TO step;
ALTER TABLE run_log RENAME COLUMN mensagem TO message;
ALTER TABLE run_log RENAME COLUMN nivel TO level;
ALTER TABLE termo RENAME COLUMN ativo TO active;
ALTER TABLE termo RENAME COLUMN config_versao_id TO config_version_id;
ALTER TABLE termo RENAME COLUMN criado_em TO created_at;
ALTER TABLE termo RENAME COLUMN origem TO source;
ALTER TABLE termo_geracao RENAME COLUMN criado_em TO created_at;
ALTER TABLE termo_geracao RENAME COLUMN modelo TO model;
ALTER TABLE termo_geracao RENAME COLUMN prompt_versao_id TO prompt_version_id;
ALTER TABLE termo_geracao RENAME COLUMN provedor TO provider;
ALTER TABLE texto_classificacao RENAME COLUMN criado_em TO created_at;
ALTER TABLE texto_classificacao RENAME COLUMN descricao TO description;
ALTER TABLE texto_classificacao RENAME COLUMN modelo TO model;
ALTER TABLE texto_classificacao RENAME COLUMN prompt_versao_id TO prompt_version_id;
ALTER TABLE texto_classificacao RENAME COLUMN provedor TO provider;
ALTER TABLE provedor RENAME TO provider;
ALTER TABLE capacidade_provedor RENAME TO provider_capability;
ALTER TABLE provedor_status RENAME TO provider_status;
ALTER TABLE config_versao RENAME TO config_version;
ALTER TABLE config_valor RENAME TO config_value;
ALTER TABLE prompt_versao RENAME TO prompt_version;
ALTER TABLE run_etapa RENAME TO run_step;
ALTER TABLE execucao_lock RENAME TO run_lock;
ALTER TABLE erro_item RENAME TO item_error;
ALTER TABLE llm_chamada RENAME TO llm_call;
ALTER TABLE rotulo RENAME TO label;
ALTER TABLE coleta_watermark RENAME TO collection_watermark;
ALTER TABLE notificacao_destinatario RENAME TO notification_recipient;
"""

DOWN = """
ALTER TABLE provider RENAME TO provedor;
ALTER TABLE provider_capability RENAME TO capacidade_provedor;
ALTER TABLE provider_status RENAME TO provedor_status;
ALTER TABLE config_version RENAME TO config_versao;
ALTER TABLE config_value RENAME TO config_valor;
ALTER TABLE prompt_version RENAME TO prompt_versao;
ALTER TABLE run_step RENAME TO run_etapa;
ALTER TABLE run_lock RENAME TO execucao_lock;
ALTER TABLE item_error RENAME TO erro_item;
ALTER TABLE llm_call RENAME TO llm_chamada;
ALTER TABLE label RENAME TO rotulo;
ALTER TABLE collection_watermark RENAME TO coleta_watermark;
ALTER TABLE notification_recipient RENAME TO notificacao_destinatario;
ALTER TABLE capacidade_provedor RENAME COLUMN capability TO capacidade;
ALTER TABLE capacidade_provedor RENAME COLUMN model TO modelo;
ALTER TABLE capacidade_provedor RENAME COLUMN provider TO provedor;
ALTER TABLE catalogo_item RENAME COLUMN active TO ativo;
ALTER TABLE catalogo_item RENAME COLUMN updated_at TO atualizado_em;
ALTER TABLE catalogo_item RENAME COLUMN created_at TO criado_em;
ALTER TABLE catalogo_item RENAME COLUMN description TO descricao;
ALTER TABLE catalogo_raw RENAME COLUMN description TO descricao;
ALTER TABLE coleta_progresso RENAME COLUMN finished_at TO concluido_em;
ALTER TABLE coleta_watermark RENAME COLUMN updated_at TO atualizado_em;
ALTER TABLE config_valor RENAME COLUMN key TO chave;
ALTER TABLE config_valor RENAME COLUMN config_version_id TO config_versao_id;
ALTER TABLE config_valor RENAME COLUMN value TO valor;
ALTER TABLE config_versao RENAME COLUMN created_at TO criado_em;
ALTER TABLE config_versao RENAME COLUMN created_by TO criado_por;
ALTER TABLE config_versao RENAME COLUMN notes TO notas;
ALTER TABLE config_versao RENAME COLUMN label TO rotulo;
ALTER TABLE documento RENAME COLUMN updated_at TO atualizado_em;
ALTER TABLE documento RENAME COLUMN created_at TO criado_em;
ALTER TABLE documento_extracao RENAME COLUMN created_at TO criado_em;
ALTER TABLE documento_extracao RENAME COLUMN cost_usd TO custo_usd;
ALTER TABLE documento_extracao RENAME COLUMN duration_ms TO duracao_ms;
ALTER TABLE documento_extracao RENAME COLUMN model TO modelo;
ALTER TABLE documento_extracao RENAME COLUMN provider TO provedor;
ALTER TABLE embedding_cache RENAME COLUMN created_at TO criado_em;
ALTER TABLE embedding_cache RENAME COLUMN dimension TO dimensao;
ALTER TABLE embedding_cache RENAME COLUMN model TO modelo;
ALTER TABLE embedding_cache RENAME COLUMN provider TO provedor;
ALTER TABLE embedding_cache RENAME COLUMN vector TO vetor;
ALTER TABLE erro_item RENAME COLUMN key TO chave;
ALTER TABLE erro_item RENAME COLUMN created_at TO criado_em;
ALTER TABLE erro_item RENAME COLUMN step TO etapa;
ALTER TABLE erro_item RENAME COLUMN message TO mensagem;
ALTER TABLE erro_item RENAME COLUMN resolved TO resolvido;
ALTER TABLE erro_item RENAME COLUMN attempts TO tentativas;
ALTER TABLE erro_item RENAME COLUMN error_type TO tipo_erro;
ALTER TABLE execucao_lock RENAME COLUMN acquired_at TO adquirido_em;
ALTER TABLE execucao_lock RENAME COLUMN expires_at TO expira_em;
ALTER TABLE export RENAME COLUMN created_at TO criado_em;
ALTER TABLE faixa_preco RENAME COLUMN config_version_id TO config_versao_id;
ALTER TABLE grupo_item RENAME COLUMN created_at TO criado_em;
ALTER TABLE grupo_permitido RENAME COLUMN active TO ativo;
ALTER TABLE grupo_permitido RENAME COLUMN updated_at TO atualizado_em;
ALTER TABLE grupo_permitido RENAME COLUMN created_at TO criado_em;
ALTER TABLE grupo_permitido RENAME COLUMN created_by TO criado_por;
ALTER TABLE grupo_permitido RENAME COLUMN name TO nome;
ALTER TABLE item RENAME COLUMN created_at TO criado_em;
ALTER TABLE item_enriquecido RENAME COLUMN created_at TO criado_em;
ALTER TABLE llm_chamada RENAME COLUMN capability TO capacidade;
ALTER TABLE llm_chamada RENAME COLUMN key TO chave;
ALTER TABLE llm_chamada RENAME COLUMN created_at TO criado_em;
ALTER TABLE llm_chamada RENAME COLUMN cost_usd TO custo_usd;
ALTER TABLE llm_chamada RENAME COLUMN duration_ms TO duracao_ms;
ALTER TABLE llm_chamada RENAME COLUMN step TO etapa;
ALTER TABLE llm_chamada RENAME COLUMN model TO modelo;
ALTER TABLE llm_chamada RENAME COLUMN prompt_version_id TO prompt_versao_id;
ALTER TABLE llm_chamada RENAME COLUMN provider TO provedor;
ALTER TABLE llm_chamada RENAME COLUMN success TO sucesso;
ALTER TABLE notificacao_destinatario RENAME COLUMN active TO ativo;
ALTER TABLE notificacao_destinatario RENAME COLUMN created_at TO criado_em;
ALTER TABLE notificacao_destinatario RENAME COLUMN name TO nome;
ALTER TABLE par RENAME COLUMN updated_at TO atualizado_em;
ALTER TABLE par RENAME COLUMN final_decision TO decisao_final;
ALTER TABLE pdm_permitido RENAME COLUMN active TO ativo;
ALTER TABLE pdm_permitido RENAME COLUMN updated_at TO atualizado_em;
ALTER TABLE pdm_permitido RENAME COLUMN created_at TO criado_em;
ALTER TABLE pdm_permitido RENAME COLUMN created_by TO criado_por;
ALTER TABLE pdm_permitido RENAME COLUMN name TO nome;
ALTER TABLE prompt RENAME COLUMN capability TO capacidade;
ALTER TABLE prompt RENAME COLUMN description TO descricao;
ALTER TABLE prompt RENAME COLUMN name TO nome;
ALTER TABLE prompt_versao RENAME COLUMN active TO ativa;
ALTER TABLE prompt_versao RENAME COLUMN created_at TO criado_em;
ALTER TABLE prompt_versao RENAME COLUMN created_by TO criado_por;
ALTER TABLE prompt_versao RENAME COLUMN notes TO notas;
ALTER TABLE prompt_versao RENAME COLUMN prompt_name TO prompt_nome;
ALTER TABLE prompt_versao RENAME COLUMN version TO versao;
ALTER TABLE provedor RENAME COLUMN api_key_updated_at TO api_key_atualizada_em;
ALTER TABLE provedor RENAME COLUMN api_key_encrypted TO api_key_cifrada;
ALTER TABLE provedor RENAME COLUMN active TO ativo;
ALTER TABLE provedor RENAME COLUMN updated_at TO atualizado_em;
ALTER TABLE provedor RENAME COLUMN capabilities TO capacidades;
ALTER TABLE provedor RENAME COLUMN cost_in_per_mtok TO custo_in_por_mtok;
ALTER TABLE provedor RENAME COLUMN cost_out_per_mtok TO custo_out_por_mtok;
ALTER TABLE provedor RENAME COLUMN cost_usd_per_call TO custo_usd_chamada;
ALTER TABLE provedor RENAME COLUMN default_model TO modelo_padrao;
ALTER TABLE provedor RENAME COLUMN name TO nome;
ALTER TABLE provedor RENAME COLUMN allows_fallback TO permite_fallback;
ALTER TABLE provedor RENAME COLUMN priority TO prioridade;
ALTER TABLE provedor RENAME COLUMN rpm_limit TO rpm_limite;
ALTER TABLE provedor_status RENAME COLUMN latency_ms TO latencia_ms;
ALTER TABLE provedor_status RENAME COLUMN message TO mensagem;
ALTER TABLE provedor_status RENAME COLUMN provider TO provedor;
ALTER TABLE provedor_status RENAME COLUMN healthy TO saudavel;
ALTER TABLE provedor_status RENAME COLUMN checked_at TO verificado_em;
ALTER TABLE rotulo RENAME COLUMN created_at TO criado_em;
ALTER TABLE rotulo RENAME COLUMN final_decision TO decisao_final;
ALTER TABLE rotulo RENAME COLUMN model TO modelo;
ALTER TABLE rotulo RENAME COLUMN source TO origem;
ALTER TABLE run RENAME COLUMN finished_at TO concluido_em;
ALTER TABLE run RENAME COLUMN config_version_id TO config_versao_id;
ALTER TABLE run RENAME COLUMN created_at TO criado_em;
ALTER TABLE run RENAME COLUMN created_by TO criado_por;
ALTER TABLE run RENAME COLUMN cost_usd TO custo_usd;
ALTER TABLE run RENAME COLUMN document_limit TO limite_documentos;
ALTER TABLE run RENAME COLUMN mode TO modo;
ALTER TABLE run RENAME COLUMN label TO rotulo;
ALTER TABLE run RENAME COLUMN cost_cap_usd TO teto_custo_usd;
ALTER TABLE run_etapa RENAME COLUMN action TO acao;
ALTER TABLE run_etapa RENAME COLUMN approved_at TO aprovado_em;
ALTER TABLE run_etapa RENAME COLUMN approved_by TO aprovado_por;
ALTER TABLE run_etapa RENAME COLUMN finished_at TO concluida_em;
ALTER TABLE run_etapa RENAME COLUMN cost_usd TO custo_usd;
ALTER TABLE run_etapa RENAME COLUMN errors TO erros;
ALTER TABLE run_etapa RENAME COLUMN step TO etapa;
ALTER TABLE run_etapa RENAME COLUMN heartbeat_at TO heartbeat_em;
ALTER TABLE run_etapa RENAME COLUMN started_at TO iniciada_em;
ALTER TABLE run_etapa RENAME COLUMN error_message TO mensagem_erro;
ALTER TABLE run_etapa RENAME COLUMN metrics TO metricas;
ALTER TABLE run_etapa RENAME COLUMN effective_params TO params_efetivos;
ALTER TABLE run_etapa RENAME COLUMN processed TO processados;
ALTER TABLE run_log RENAME COLUMN context TO contexto;
ALTER TABLE run_log RENAME COLUMN created_at TO criado_em;
ALTER TABLE run_log RENAME COLUMN step TO etapa;
ALTER TABLE run_log RENAME COLUMN message TO mensagem;
ALTER TABLE run_log RENAME COLUMN level TO nivel;
ALTER TABLE termo RENAME COLUMN active TO ativo;
ALTER TABLE termo RENAME COLUMN config_version_id TO config_versao_id;
ALTER TABLE termo RENAME COLUMN created_at TO criado_em;
ALTER TABLE termo RENAME COLUMN source TO origem;
ALTER TABLE termo_geracao RENAME COLUMN created_at TO criado_em;
ALTER TABLE termo_geracao RENAME COLUMN model TO modelo;
ALTER TABLE termo_geracao RENAME COLUMN prompt_version_id TO prompt_versao_id;
ALTER TABLE termo_geracao RENAME COLUMN provider TO provedor;
ALTER TABLE texto_classificacao RENAME COLUMN created_at TO criado_em;
ALTER TABLE texto_classificacao RENAME COLUMN description TO descricao;
ALTER TABLE texto_classificacao RENAME COLUMN model TO modelo;
ALTER TABLE texto_classificacao RENAME COLUMN prompt_version_id TO prompt_versao_id;
ALTER TABLE texto_classificacao RENAME COLUMN provider TO provedor;
ALTER TYPE capability RENAME VALUE 'matching' TO 'pareamento';
ALTER TYPE extraction_strategy RENAME VALUE 'window' TO 'janela';
ALTER TYPE extraction_strategy RENAME VALUE 'full' TO 'completa';
ALTER TYPE extraction_strategy RENAME VALUE 'vision' TO 'visao';
ALTER TYPE step_status RENAME VALUE 'not_started' TO 'nao_iniciada';
ALTER TYPE step_status RENAME VALUE 'awaiting_approval' TO 'aguardando_aprovacao';
ALTER TYPE step_status RENAME VALUE 'running' TO 'executando';
ALTER TYPE step_status RENAME VALUE 'finished' TO 'concluida';
ALTER TYPE step_status RENAME VALUE 'outdated' TO 'desatualizada';
ALTER TYPE step_status RENAME VALUE 'failed' TO 'falhou';
ALTER TYPE step_status RENAME VALUE 'cancelled' TO 'cancelada';
ALTER TYPE step_status RENAME VALUE 'skipped' TO 'pulada';
ALTER TYPE run_action RENAME VALUE 'update' TO 'atualizar';
ALTER TYPE run_action RENAME VALUE 'resume' TO 'retomar';
ALTER TYPE run_action RENAME VALUE 'redo' TO 'refazer';
ALTER TYPE run_mode RENAME VALUE 'assisted' TO 'assistido';
ALTER TYPE run_mode RENAME VALUE 'sequential' TO 'sequencial';
ALTER TYPE run_mode RENAME VALUE 'sample' TO 'amostra';
ALTER TYPE run_mode RENAME VALUE 'simulation' TO 'simulacao';
ALTER TYPE run_status RENAME VALUE 'open' TO 'aberto';
ALTER TYPE run_status RENAME VALUE 'finished' TO 'concluido';
ALTER TYPE run_status RENAME VALUE 'aborted' TO 'abortado';
ALTER TYPE capability RENAME TO capacidade;
ALTER TYPE step_status RENAME TO status_etapa;
ALTER TYPE run_action RENAME TO acao_execucao;
ALTER TYPE extraction_strategy RENAME TO estrategia_extracao;
ALTER TYPE run_mode RENAME TO modo_run;
ALTER TYPE run_status RENAME TO status_run;
"""


def upgrade() -> None:
    op.execute(UP)


def downgrade() -> None:
    op.execute(DOWN)
